version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: ./server/dockerfile
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    networks:
      - futebasssss-network


  frontend: 
    build: 
      context: .
      dockerfile: ./front/dockerfile
    env_file: 
      - ./front/.env
    ports:
      - "80:80"
    networks:
      - futebasssss-network

networks:
  futebasssss-network:
    external: true
