version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: ./server/dockerfile
    ports:
      - "3000:3000"
    networks:
      - bridge


  frontend: 
    build: 
      context: .
      dockerfile: ./front/dockerfile
    ports:
      - "80:80"
    networks:
      - bridge

networks:
  bridge:
    external: true
