version: '3.8'

services:
  server:
    image: 
      futebasssss-server
    build: 
      context: .
      dockerfile: ./server/dockerfile
    env_file:
      - ./server/.env
    ports:
      - "3001:3000"
    networks:
      - futebasssss-network


  frontend:
    image: 
      futebasssss-frontend    
    build: 
      context: .
      dockerfile: ./front/dockerfile
    env_file: 
      - ./front/.env
    ports:
      - "8081:80"
    networks:
      - futebasssss-network

networks:
  futebasssss-network:
    external: true
