FROM node:20-alpine as builder

WORKDIR /app

COPY . .

RUN yarn install --frozen-lockfile
RUN yarn build:constants

WORKDIR /app/front
RUN yarn install
RUN yarn build

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/front/dist /usr/share/nginx/html
COPY deploy/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]