name: Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Deploy via SSH (usuário e senha)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          # Porta default é 22, se for outra especifique, ex: port: 2222
          script: |
            # navigate into vps directory
            cd /var/www/vhosts/futebasssss.com.br/httpdocs
            
            git pull origin main
            
            # updates docker containers
            docker compose pull
            docker compose up -d --force-recreate --build
